### ISSUE TITLE
Failed to run 3D Rayleigh-Benard simulation

### ISSUE THREAD

**Issue by thw1021** [spectralDNS/spectralDNS#36]
Dear @mikaem 
Thanks for your work. I have some problems about the code for simulating 3D Rayleigh-Benard convection. Could you give me some suggestions, please ?

1. There seems to be a problem with the optimization both in parallel and serial simulation. I am not sure whether this will hurt the results.
![Screenshot from 2020-05-23 22-46-07](https://user-images.githubusercontent.com/17957650/82733984-50fb2b00-9d4a-11ea-98ee-daf698ad7e77.png)

2. When I try to run the code in parallel, an error occurred. It is caused by [this line](https://github.com/spectralDNS/spectralDNS/blob/0514d2ec146e8824a673d264e4feea55e65c2da7/demo/RayleighBenard.py#L95). But I have not figured out the mean of these parameters. (The code can run without such problem in serial)
![Screenshot from 2020-05-23 22-46-23](https://user-images.githubusercontent.com/17957650/82734024-9a4b7a80-9d4a-11ea-8f50-5c3c515756c5.png)

3. I commented out [this line](https://github.com/spectralDNS/spectralDNS/blob/0514d2ec146e8824a673d264e4feea55e65c2da7/demo/RayleighBenard.py#L95), then code can run in parallel (still have the problem about optimization). Based on your suggestion, I try to visualize the generated data using following snippet, but it didn't work. I searched a lot but still failed to solve this issue.
```
# visualize the generated data
from mpi4py_fft import generate_xdmf
import argparse
import glob, os
parser = argparse.ArgumentParser(description="visualize the generated data")
parser.add_argument("-p", "--PATH", type=str, default="./", help="path to the generated data (should end with a /)")
args = parser.parse_args()
path = args.PATH
os.chdir(path)
for file in glob.glob("*.h5"):
    print("generate xdmf file for {}".format(file))
    generate_xdmf(file)
```
![Screenshot from 2020-05-23 22-28-37](https://user-images.githubusercontent.com/17957650/82734105-1d6cd080-9d4b-11ea-9e69-8069a9b1f790.png)

**Comment by mikaem** [comment]
Hi
> There seems to be a problem with the optimization both in parallel and serial simulation. I am not sure whether this will hurt the results.

You need to use 

    mpirun -np 24 python RayleighBenard.py --optimization cython KMMRK3_RB

> When I try to run the code in parallel, an error occurred. It is caused by this line. But I have not figured out the mean of these parameters. (The code can run without such problem in serial)

The Stats sampling class seems to be broken. I have pushed a quick fix, but I cannot guarantee that everything works yet without further testing. I haven't looked at this solver for quite a while and I notice some things that need to be changed.

> Based on your suggestion, I try to visualize the generated data using following snippet, but it didn't work. I searched a lot but still failed to solve this issue.

Looks like you're trying to use `generate_xdmf` on all cores. You need to call this function with only one core. Try

    if solver.rank == 0:
        generate_xdmf('filename')

**Comment by thw1021** [comment]
Thank you.

1. I tried but the optimization problem still occurred.
![Screenshot from 2020-05-24 08-41-54](https://user-images.githubusercontent.com/17957650/82743242-34d3aa00-9d9b-11ea-95dc-2abefbfa798c.png)

2. The fix works. At least the simulation in parallel can run without error. Thank you.

3. I have tried to add `solver.rank == 0` or `comm.Get_rank() == 0` in [`RayleighBenard.py`](https://github.com/spectralDNS/spectralDNS/blob/master/demo/RayleighBenard.py). Still got same error.
![Screenshot from 2020-05-24 09-34-34](https://user-images.githubusercontent.com/17957650/82743765-613ef480-9da2-11ea-9ac8-74963e4b5097.png)
I added the following snippet at the end of [`RayleighBenard.py`](https://github.com/spectralDNS/spectralDNS/blob/master/demo/RayleighBenard.py).
```
    for file in glob.glob("*.h5"):
        print("generate xdmf file for {}".format(file))
        if comm.Get_rank() == 0:
            generate_xdmf(file)
```

**Comment by mikaem** [comment]
1. This is something with your installation. Did you run install? Or

    python setup.py build_ext -i

to compile the cython code? If the cython code is not compiled then there can be no optimization.
3. You cannot use 'generate_xdmf' for all 'h5' files. And glob.glob gives you also the stats file.

**Comment by thw1021** [comment]
1. Both `python setup.py install` and `python setup.py build_ext -i` have been used. Still see the optimization problems shown [here](https://github.com/spectralDNS/spectralDNS/issues/36#issuecomment-633164290).

Install via `python setup.py install` (part of output was omitted):
![Screenshot from 2020-05-24 20-26-34](https://user-images.githubusercontent.com/17957650/82754113-6d0bd480-9dfd-11ea-91bc-f240aea72526.png)
![Screenshot from 2020-05-24 20-27-18](https://user-images.githubusercontent.com/17957650/82754115-709f5b80-9dfd-11ea-8d11-f0a84ac0aa16.png)

Install via `python setup.py build_ext -i`:
![Screenshot from 2020-05-24 20-27-33](https://user-images.githubusercontent.com/17957650/82754117-7137f200-9dfd-11ea-9982-0137134e20f2.png)

3. I have modified the code. The `generate_xdmf` seemingly doesn't work (no xdmf files).
![Screenshot from 2020-05-24 20-52-28](https://user-images.githubusercontent.com/17957650/82754611-97ab5c80-9e00-11ea-9012-5b695d86ab8c.png)
```
    if solver.rank == 0:
        print("generate xdmf file for {}".format('_'.join((context.hdf5file.filename, 'c'))+'.h5'))
        generate_xdmf('_'.join((context.hdf5file.filename, 'c'))+'.h5')
        print("generate xdmf file for {}".format('_'.join((context.hdf5file.filename, 'w'))+'.h5'))
        generate_xdmf('_'.join((context.hdf5file.filename, 'w'))+'.h5')
```

**Comment by mikaem** [comment]
1. What do you get from

    from spectralDNS.optimization import cython_double

?

3. Are KMM_RB_677a_w.h5 and KMM_RB_677a_c.h5 empty? You have to use parameters --checkpoint N or --write_result M to actually store some data every N or M timestep. See

    python RayleighBenard.py -h

or the config.py file for options.

**Comment by thw1021** [comment]
1. Seems no problem.
![Screenshot from 2020-05-24 22-37-56](https://user-images.githubusercontent.com/17957650/82757298-1bba1000-9e12-11ea-99b3-4c5cc39270d8.png)


3. ooo, yes, these two files are empty. Sorry, I didn't check that. 
`--write_result M` works. But results are slices of the flow domain. How can I got the results of full domain like you presented in this repo ?

`--checkpoint N` got an error.
![Screenshot from 2020-05-24 22-37-56](https://user-images.githubusercontent.com/17957650/82757050-908c4a80-9e10-11ea-8f76-7d487e06bcdc.png)

Really sorry for bothering you a lot. Thanks for your help.

**Comment by mikaem** [comment]
Actually, there's no problem with optimizations, it's just that cython-routines have not been implemented for those that are reported (assembleAB, add_linear).

You cannot visualize checkpoint-data because only complex coefficients are stored in that file (U_hat, P_hat). So you only visualize KMM_RB_677a_w.h5. To get complete datasets modify

    context.hdf5file.results['data'] = {'U0': [(context.U[0], [slice(None), slice(None), 0]),
                                               (context.U[0], [slice(None), 0, slice(None)])],
                                        'U1': [(context.U[1], [slice(None), slice(None), 0]),
                                               (context.U[1], [slice(None), 0, slice(None)])],
                                        'U2': [(context.U[2], [slice(None), slice(None), 0]),
                                               (context.U[2], [slice(None), 0, slice(None)])],
                                        'phi': [(context.phi, [slice(None), slice(None), 0]),
                                                (context.phi, [slice(None), 0, slice(None)])]
                                       }

to, e.g., 

    context.hdf5file.results['data'] = {'U0': [context.U[0]],
                                        'U1': [context.U[1]],
                                        'U2': [context.U[2]],
                                        'phi': [context.phi]
                                       }

**Comment by thw1021** [comment]
OK. Thank you.

Sorry, can you make it more specific ? By 'complex coefficients', do you mean the coefficients of FFT used to discretize the governing equations ? And these coefficients are stored in `KMM_RB_677a_c.h5` ?
The variables of flow filed are stored in `KMM_RB_677a_w.h5`. For present code, they are the three components of velocity (`U0`, `U1`, `U2`) and temperature (`phi`).

**Comment by Daniel-J123** [comment]
hi ,
have you solved this issue？i want to extract datasets about velocity filed and visualize it but i don't know how to do ？

**Comment by thw1021** [comment]
Hi, sorry I have not dug into the code due to busy with some other things recently. But following the [suggestions ](https://github.com/spectralDNS/spectralDNS/issues/36#issuecomment-633251120)of Mikael, you can get full/partial flow field. Of course, you can also use software like tecplot or paraview to extract slices of the velocity filed.
